#!/bin/bash
# /usr/bin/i3exit

# with openrc use loginctl
[[ $(cat /proc/1/comm) == "runit" ]] 

case "$1" in
    lock)
        blurlock
        ;;
    logout)
        i3-msg exit
        ;;
    switch_user)
        dm-tool switch-to-greeter
        ;;
    suspend)
        blurlock && sudo zzz 
        ;;
    hibernate)
        blurlock && sudo ZZZ
        ;;
    reboot)
        sudo reboot
        ;;
    shutdown)
         sudo shutdown -h now        
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
