#!/bin/bash
# /usr/bin/blurlock

# take screenshot
grim /tmp/screenshot.png

# blur it
convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
rm /tmp/screenshot.png

# lock the screen
#i3lock -i /tmp/screenshotblur.png
swaylock -i /tmp/screenshotblur.png

exit 0
