#!/usr/bin/env sh


kill -9 `pidof waybar`

# Wait until the processes have been shut down
while pgrep -u $UID -x waybar >/dev/null; do sleep 1; done
# Launch top bar
waybar & #disown

echo "Waybar launched..."
